### ISSUE TITLE
Docker stopped working; Rebuilding pull wrong image from GitHub

### ISSUE THREAD

**Issue by zuidwijk** [xirixiz/dsmr-reader-docker#145]
```CLI
$ docker logs dsmr
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] Either the current release is out of sync, or no version has been installed yet! Installing null...
/dsmr /
--2020-11-02 10:37:58--  https://github.com/dennissiemensma/dsmr-reader/archive/null.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/dsmrreader/dsmr-reader/archive/null.tar.gz [following]
--2020-11-02 10:37:58--  https://github.com/dsmrreader/dsmr-reader/archive/null.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/dsmrreader/dsmr-reader/tar.gz/null [following]
--2020-11-02 10:37:59--  https://codeload.github.com/dsmrreader/dsmr-reader/tar.gz/null
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-02 10:37:59 ERROR 404: Not Found.

tar: can't open 'null.tar.gz': No such file or directory
/
cp: can't stat '/dsmr/dsmrreader/provisioning/django/settings.py.template': No such file or directory
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/dsmr/dsmrreader/provisioning/requirements/base.txt'
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Collecting psycopg2
  Downloading psycopg2-2.8.6.tar.gz (383 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.6-cp38-cp38-linux_x86_64.whl size=145223 sha256=c45dd66d7b1249326de059611fe1f9522209442a263dc5cea3ee2f7ef43da8ce
  Stored in directory: /root/.cache/pip/wheels/70/5e/69/8a020d78c09043156a7df0b64529e460fbd922ca065c4b795c
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.6
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
cp: can't stat '/dsmr/dsmrreader/provisioning/nginx/dsmr-webinterface': No such file or directory
[ INFO ] Verifying if Postgres in running...
[ INFO ] Running post configuration...
/usr/local/bin/python3: can't open file '/dsmr/manage.py': [Errno 2] No such file or directory
/usr/local/bin/python3: can't open file '/dsmr/manage.py': [Errno 2] No such file or directory
/usr/local/bin/python3: can't open file '/dsmr/manage.py': [Errno 2] No such file or directory
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
2020-11-02 10:38:07,887 INFO Included extra file "/etc/supervisor.d/supervisord.ini" during parsing
2020-11-02 10:38:07,887 INFO Set uid to user 0 succeeded
2020-11-02 10:38:07,890 INFO RPC interface 'supervisor' initialized
2020-11-02 10:38:07,890 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-02 10:38:07,890 INFO supervisord started with pid 160
2020-11-02 10:38:08,894 INFO spawned: 'dsmr_backend' with pid 162
2020-11-02 10:38:08,896 INFO spawned: 'dsmr_datalogger' with pid 163
2020-11-02 10:38:08,897 INFO spawnerr: can't find command 'gunicorn'
2020-11-02 10:38:08,898 INFO spawned: 'nginx' with pid 164
2020-11-02 10:38:08,909 INFO exited: dsmr_backend (exit status 2; not expected)
2020-11-02 10:38:08,909 INFO exited: dsmr_datalogger (exit status 2; not expected)
2020-11-02 10:38:09,914 INFO spawned: 'dsmr_backend' with pid 169
2020-11-02 10:38:09,916 INFO spawned: 'dsmr_datalogger' with pid 170
2020-11-02 10:38:09,917 INFO spawnerr: can't find command 'gunicorn'
2020-11-02 10:38:09,917 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 10:38:09,928 INFO exited: dsmr_backend (exit status 2; not expected)
2020-11-02 10:38:09,929 INFO exited: dsmr_datalogger (exit status 2; not expected)
2020-11-02 10:38:11,934 INFO spawned: 'dsmr_backend' with pid 171
2020-11-02 10:38:11,937 INFO spawned: 'dsmr_datalogger' with pid 172
2020-11-02 10:38:11,938 INFO spawnerr: can't find command 'gunicorn'
2020-11-02 10:38:11,949 INFO exited: dsmr_backend (exit status 2; not expected)
2020-11-02 10:38:11,950 INFO exited: dsmr_datalogger (exit status 2; not expected)
2020-11-02 10:38:14,956 INFO spawned: 'dsmr_backend' with pid 173
2020-11-02 10:38:14,960 INFO spawned: 'dsmr_datalogger' with pid 174
2020-11-02 10:38:14,960 INFO spawnerr: can't find command 'gunicorn'
2020-11-02 10:38:14,960 INFO gave up: dsmr_webinterface entered FATAL state, too many start retries too quickly
2020-11-02 10:38:14,972 INFO exited: dsmr_backend (exit status 2; not expected)
2020-11-02 10:38:14,973 INFO exited: dsmr_datalogger (exit status 2; not expected)
2020-11-02 10:38:18,979 INFO spawned: 'dsmr_backend' with pid 175
2020-11-02 10:38:18,982 INFO spawned: 'dsmr_datalogger' with pid 176
2020-11-02 10:38:18,995 INFO exited: dsmr_backend (exit status 2; not expected)
2020-11-02 10:38:18,996 INFO exited: dsmr_datalogger (exit status 2; not expected)
```

**Comment by zuidwijk** [comment]
Ok, so I pulled the latest image again, stopped and removed dsmr container and rebuild it, after which it worked again:
```CMD
$ docker pull xirixiz/dsmr-reader-docker:latest
latest: Pulling from xirixiz/dsmr-reader-docker
188c0c94c7c5: Pull complete 
55578f60cda7: Pull complete 
692da2fcb614: Pull complete 
599e2857d4f0: Pull complete 
4b3bf1abad55: Pull complete 
01d4f1bb092e: Pull complete 
12af67e1f743: Pull complete 
9f69241f02ed: Pull complete 
4b4c6ee3d498: Pull complete 
42c82497a72e: Pull complete 
842a35ce163b: Pull complete 
3b39c1b97bb3: Pull complete 
9d377d31ec56: Pull complete 
Digest: sha256:b02b82ca92cfa4911c7a49f9dd833c64c57e49d5482078722efce047107b2c76
Status: Downloaded newer image for xirixiz/dsmr-reader-docker:latest
docker.io/xirixiz/dsmr-reader-docker:latest
$ docker stop dsmr
dsmr
$ docker rm dsmr
dsmr
$ docker-compose up -d
dsmrdb is up-to-date
Creating dsmr ... done
$ docker logs dsmr
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Verifying if Postgres in running...
[ INFO ] Configuring DSMR in standlone datalogger mode....
[ INFO ] Running post configuration...
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  No migrations to apply.

561 static files copied to '/var/www/dsmrreader/static'.
Traceback (most recent call last):
  File "/dsmr/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/dsmr/dsmr_backend/management/commands/dsmr_superuser.py", line 17, in handle
    default=config('DSMRREADER_ADMIN_PASSWORD')
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: DSMRREADER_ADMIN_PASSWORD not found. Declare it as envvar or define a default value.
[ INFO ] Checking for HTTP AUTHENTICATION configuration...
[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...
[ INFO ] Starting supervisord...
[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log
2020-11-02 10:45:55,065 INFO Included extra file "/etc/supervisor.d/supervisord.ini" during parsing
2020-11-02 10:45:55,065 INFO Set uid to user 0 succeeded
2020-11-02 10:45:55,069 INFO RPC interface 'supervisor' initialized
2020-11-02 10:45:55,069 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-02 10:45:55,069 INFO supervisord started with pid 16
2020-11-02 10:45:56,072 INFO spawned: 'dsmr_backend' with pid 18
2020-11-02 10:45:56,076 INFO spawned: 'dsmr_datalogger' with pid 19
2020-11-02 10:45:56,077 INFO spawned: 'dsmr_webinterface' with pid 20
2020-11-02 10:45:56,078 INFO spawned: 'nginx' with pid 21
2020-11-02 10:45:57,640 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 10:45:57,640 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 10:45:57,640 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-02 10:45:59,642 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
$ 
```

**Comment by zuidwijk** [comment]
I was running version 4.5 and now after the pull version 4.6... Still wondering if the could be due to an automated update?

**Comment by zuidwijk** [comment]
I wonder how this relates....

I have a backup script, running every night at 3am:
````
$ cat sql_backup.sh 
#!/bin/bash

/usr/bin/docker stop dsmr
/usr/bin/docker exec -t dsmrdb pg_dumpall -c -U dsmrreader | /bin/gzip > /opt/dsmr/sql_backup/dsmrreader.$(date +%F).sql.gz
/usr/bin/docker start dsmr

## Alleen 3 nieuwste bewaren
find /opt/dsmr/sql_backup -mtime +3 -delete
````
The last reading was 3:01 and than stopped logging (assuming then the same error logging was as I posted in opening post)

So stopping the container, perform a backup and restarting the container doesn't work reliable ...

**Comment by xirixiz** [comment]
Release 4.6 was released last night: https://github.com/dsmrreader/dsmr-reader (new url)

**Comment by xirixiz** [comment]
I missed these changes, creating a new image now.
https://dsmr-reader.readthedocs.io/nl/v4/env_settings.html

**Comment by xirixiz** [comment]
Which tag are you using of the Docker image? Checking your logs you're using an outdated version....

**Comment by Tralapo** [comment]
I did a docker-compose pull last friday and since then DSMR stopped working. Came here this morning to check the latest docker-compose file in the repo and made sure I updated mine, but still no working DSMR.

I see it's a bigger problem? I am using xirixiz/dsmr-reader-docker:latest-arm32v7. Here's my log. Let me know if I have to check something else.

```
docker logs dsmr
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] Either the current release is out of sync, or no version has been installed yet! Installing null...
/dsmr /
--2020-11-02 11:29:11--  https://github.com/dennissiemensma/dsmr-reader/archive/null.tar.gz
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/dsmrreader/dsmr-reader/archive/null.tar.gz [following]
--2020-11-02 11:29:15--  https://github.com/dsmrreader/dsmr-reader/archive/null.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/dsmrreader/dsmr-reader/tar.gz/null [following]
--2020-11-02 11:29:16--  https://codeload.github.com/dsmrreader/dsmr-reader/tar.gz/null
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-02 11:29:20 ERROR 404: Not Found.

tar: can't open 'null.tar.gz': No such file or directory
/
cp: can't stat '/dsmr/dsmrreader/provisioning/django/settings.py.template': No such file or directory
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/dsmr/dsmrreader/provisioning/requirements/base.txt'
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Collecting psycopg2
  Downloading psycopg2-2.8.6.tar.gz (383 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): still running...
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.6-cp38-cp38-linux_armv7l.whl size=126739 sha256=387c29cfa4c893dcf9167255b9ce8f455b55b05da448f8377856ddde1                                                                                                                                                                e06939b
  Stored in directory: /root/.cache/pip/wheels/70/5e/69/8a020d78c09043156a7df0b64529e460fbd922ca065c4b795c
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.6
WARNING: You are using pip version 20.2.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
cp: can't stat '/dsmr/dsmrreader/provisioning/nginx/dsmr-webinterface': No such file or directory
[ INFO ] Verifying if Postgres in running...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
[ FAIL ] Could not connect to database server. Aborting...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying if DSMR_RELEASE has been set correctly!
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Using the latest release.
[ INFO ] DSMR already installed with the desired release. Continuing...
[ INFO ] Verifying if Postgres in running...
```

**Comment by xirixiz** [comment]
I see you are using old tag conventions (see the README for valid tags), I also just removed those to prevent any confusion. The error appeared with the images you are using as Dennis moved DSMR Reader to a different github repository (business).

Just use ```xirixiz/dsmr-reader-docker:latest``, which is suitable for any architecture (stable release).

But again, also update your environment settings: https://dsmr-reader.readthedocs.io/nl/v4/env_settings.html

**Comment by Tralapo** [comment]
Rebuilding now. DSMR log looks good now. 
I updated my docker-compose file with the latest settings as shown in the repo here and saw you changed PostgreSQL from 10.5 to 12. This does not seem to work, is there some migration steps I missed?

```
2020-11-02 12:11:19.455 CET [1] FATAL:  database files are incompatible with server
2020-11-02 12:11:19.455 CET [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 12.4.
```

**Comment by xirixiz** [comment]
Hi you cannot just upgrade to a higher Postgres version. You need to execute the following steps to do so (or stick to version 10.x):

```
- stop dsmr
- backup the database
- stop dsmrdb
- rename the db folder to something (.old), and create a new one with the samen name
- update docker-compose with the new postgres version
- start dsmrdb
- restore the backup
- restart dsmrdb
- start dsmr
```
... Bob's your uncle.

**Comment by Tralapo** [comment]
Made it work, thx!

**Comment by xirixiz** [comment]
You're fast! Good work!

**Comment by zuidwijk** [comment]
> I missed these changes, creating a new image now.
> https://dsmr-reader.readthedocs.io/nl/v4/env_settings.html


> Which tag are you using of the Docker image? Checking your logs you're using an outdated version....

Well to be honest, I didn't change anything to my docker-compose since v4.1. After that, It seems to automatically upgrade itself ... 

Looking at the new settings:
```
Name before v4.5    ->      New name since v4.5
-----------------------------------------------
SECRET_KEY          ->      DJANGO_SECRET_KEY
DB_ENGINE           ->      DJANGO_DATABASE_ENGINE
DB_HOST             ->      DJANGO_DATABASE_HOST
DB_PORT             ->      DJANGO_DATABASE_PORT
DB_NAME             ->      DJANGO_DATABASE_NAME
DB_USER             ->      DJANGO_DATABASE_USER
DB_PASS             ->      DJANGO_DATABASE_PASSWORD
CONN_MAX_AGE        ->      DJANGO_DATABASE_CONN_MAX_AGE
TZ                  ->      DJANGO_TIME_ZONE
DSMR_USER           ->      DSMRREADER_ADMIN_USER
DSMR_PASSWORD       ->      DSMRREADER_ADMIN_PASSWORD
```
This is my docker-compose:
```YAML
version: '3.6'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
      - /dev/:/dev/:ro
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=true
      - SD_AUTORESTART_MQTT=true
      - DSMR_USER=****
      - DSMR_PASSWORD=****
      - SD_AUTOSTART_DATALOGGER=true
      - DSMR_RELEASE=latest
      
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    labels:
      - traefik.backend=dsmr
      - traefik.frontend.rule=Host:****
      - traefik.frontend.entrypoint=https
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=80
      
networks:
    default:
        external:
            name: traefik
```

So I should change it to this?:
```YAML
version: '3.6'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
      - /dev/:/dev/:ro
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=true
      - SD_AUTORESTART_MQTT=true
      - DSMRREADER_ADMIN_USER=****
      - DSMRREADER_ADMIN_PASSWORD=****
      - SD_AUTOSTART_DATALOGGER=true
      - DSMR_RELEASE=latest
    ports:
      - 7777:80
      - 7779:443
    labels:
      - traefik.backend=dsmr
      - traefik.frontend.rule=Host:****
      - traefik.frontend.entrypoint=https
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=80
      
networks:
    default:
        external:
            name: traefik
```

Should I upgrade to 12? Or stick to 10?

> Hi you cannot just upgrade to a higher Postgres version. You need to execute the following steps to do so (or stick to version 10.x):
> 
> ```
> - stop dsmr
> - backup the dsmrdb database (see readme)
> - validate the dsmrdb backup!
> - stop dsmrdb
> - rename the db folder containing the database data to something (.old)
> - create a new db folder with the same name as specified for de db files in docker-compose (so the same name as the folder you renamed in the previous step)
> - update docker-compose with the new postgres version
> - start dsmrdb (it's an empty but valid postgres 12 db now).
> - restore the database backup created in step 2 (see readme)
> - restart dsmrdb
> - start dsmr
> ```
> 
> ... Bob's your uncle.
> 
> I did this last week as Postgres 10 is becoming old :). Everything went fine.

**Comment by xirixiz** [comment]
Run ```docker pull xirixiz/dsmr-reader-docker:latest```

Change it to:
```yaml
version: '3.8'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN    
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
      - /dev/:/dev/:ro
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - DSMRREADER_ADMIN_USER=****
      - DSMRREADER_ADMIN_PASSWORD=****
    ports:
      - 7777:80
      - 7779:443
    labels:
      - traefik.backend=dsmr
      - traefik.frontend.rule=Host:****
      - traefik.frontend.entrypoint=https
      - traefik.docker.network=traefik
      - traefik.enable=true
      - traefik.port=80
      
networks:
    default:
        external:
            name: traefik
```

You could consider indeed an upgrade to Postgres 12. In the past the base Docker images for DSMR didn't support the Postgres 12 client, but it has been included for a while now. In order to keep things updated, I would upgrade to Postgres 12.

**Comment by xirixiz** [comment]
...ah good, you found out already ;)

**Comment by ronniebee** [comment]
Hi,

I'm a newbee on linux and terminal

ronniebee@ronald:~/docker$ ls -l
total 52
drwxrwxr-x+  2 ronniebee ronniebee 4096 dec 27  2019 db
drwxrwxr-x+  3 ronniebee ronniebee 4096 dec 23  2019 db:
drwxrwxr-x+  2 ronniebee ronniebee 4096 dec 23  2019 db-dsmr
-rw-rw-r--+  1 ronniebee ronniebee  824 nov 17 22:37 docker-compose.yaml
drwxr-xr-x+  3 root      root      4096 dec 27  2019 dsmr
drwxrwxr-x+  3 root      root      4096 nov 18 03:00 dsmr_backups
drwx------+ 19        70 root      4096 nov 17 22:43 dsmrdb

When I look at my docker directory I see the above.  I don't know what to rename since I made several directories a long time ago trying to get it dsmr working ( and did not know what I was doing :-)) is it the last one (root created?) or de db: (second)

sorry, I'm not an expert :-(

**Comment by xirixiz** [comment]
Looking at the date and owner, I suppose dsmrdb is the one used. However, if you share the content of your docker-compose file, then we're 100% sure.

...and you have to start somewhere learning Linux, so don't worry ;)

**Comment by ronniebee** [comment]
Hi, thx for the quick reply.
my compose is 

version: '3.8'

services:
  dsmrdb:
    image: postgres:10-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:

**Comment by xirixiz** [comment]
This means you're indeed making use of ```./dsmrdb:/var/lib/postgresql/data```

This line means that in the current directory of your docker-compose file (```./```) the folder ```dsmrdb``` is mounted in the Docker container as ```/var/lib/postgresql/data```

**Comment by ronniebee** [comment]
Ok, I'll try to rename  this one in dsmrd.old and then create a new one ( following your inx).
Let you know. 

PS I can remove the:

drwxrwxr-x+ 2 ronniebee ronniebee 4096 dec 27 2019 db
drwxrwxr-x+ 3 ronniebee ronniebee 4096 dec 23 2019 db:
drwxrwxr-x+ 2 ronniebee ronniebee 4096 dec 23 2019 db-dsmr

seems to be empty ones.

Thx so far, much appreciated!

**Comment by xirixiz** [comment]
I think you can, but you need to decide yourself ofcourse. Be carefull removing the one with the colon, for that folder use ```rm -r "db:"```, or escape the colon otherwise.

https://superuser.com/questions/468685/how-to-remove-a-folder-which-starts-with-a-colon/468686

**Comment by ronniebee** [comment]
Yes! succeeded... Many thx Bram!
