### ISSUE TITLE
Containers blijven herstarten

### ISSUE THREAD

**Issue by Tralapo** [xirixiz/dsmr-reader-docker#171]
## Setup/Architecture information
Raspberry Pi 3B, Raspbian

## Configuration

```yaml

### DSMR Database en Reader ###
  dsmrdb:
    image: postgres:12-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    image: xirixiz/dsmr-reader-docker:latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/dsmr_backups:/dsmr/backups
    environment:
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0


```

## Describe the bug

Gebruik deze setup al maanden naar volle tevredenheid, maar gisteren ging het ineens mis.
Zoals gebruikelijk wilde ik alles update door een `docker-compose pull` en daarna een `docker-compose up -d`, niets bijzonders zou je zeggen. Ook niets gewijzigd aan de compose-file.

Maar sinds die actie, doen zowel de DSMR als DSMRDB container niets anders dan elke 15-20 seconden opnieuw opstarten, tot op een punt dat de load op de Raspberry zo hoog wordt dat 'ie helemaal niets meer doet.

Heb geprobeerd de database te verwijderen en opnieuw op te tuigen zoals beschreven in de README, maar dat lukt niet eens omdat dsmrdb niet lang genoeg up blijft.

```
pi@raspberrypi:[~] sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
dropdb: error: could not connect to database template1: FATAL:  the database system is starting up

pi@raspberrypi:[~] sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: read init-p: connection reset by peer: unknown

pi@raspberrypi:[~] sudo docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
dropdb: error: could not connect to database template1: FATAL:  the database system is starting up

```

Ik heb echt geen flauw idee waar dit ineens vandaan komt of waar ik een oplossing moet zoeken, kan ook niet wijs worden uit de logs:

## Debug log

In de log van dsmr zie ik inderdaad terug dat hij niet kan connecten met de database

```text

[ FAIL ] Could not connect to database server. Exiting...
[ INFO ] Removing existing PID files...
[ INFO ] Creating log directory...
[ INFO ] Fixing /dev/ttyUSB* security...
[ INFO ] Verifying if the DSMR web credential variables have been set...
[ INFO ] Verifying Database connectivity...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "dsmrdb" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dsmr/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/shell.py", line 87, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "dsmrdb" (172.18.0.2) and accepting
        TCP/IP connections on port 5432?

[ FAIL ] Could not connect to database server. Exiting...

```

De log for dsmrdb geeft (heel vaak) het volgende, met een gekke timestamp

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

1970-04-29 13:25:44.010 CET [1] LOG:  starting PostgreSQL 12.5 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
1970-04-29 13:25:44.010 CET [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
1970-04-29 13:25:44.010 CET [1] LOG:  listening on IPv6 address "::", port 5432
1970-04-29 13:25:44.010 CET [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
1970-04-29 13:25:44.010 CET [22] FATAL:  the database system is starting up
1970-04-29 13:25:44.010 CET [1] LOG:  startup process (PID 21) was terminated by signal 11: Segmentation fault
1970-04-29 13:25:44.010 CET [1] LOG:  aborting startup due to startup process failure
1970-04-29 13:25:44.010 CET [1] LOG:  database system is shut down
```

**Comment by xirixiz** [comment]
Kan je eens proberen de ```postgres:12``` image te gebruiken. De afgelopen tijd krijg ik vaker meldingen binnen over de Posgres Alpine image. Verder zie ik de melding:

```PostgreSQL Database directory appears to contain a database; Skipping initialization```

Heb je de versie van Postgres bijgewerkt of gebruik je 12 al een tijd? Je kan ook alles stoppen en ```./data/dsmrdb``` leegmaken, en vervolgens alles weer starten.

**Comment by Tralapo** [comment]
Nee, ik heb de versie niet gewijzigd. Die had ik altijd al op `postgres:12-alpine` staan. De `appears to contain a database`-melding was waarschijnlijk omdat ik dus probeerde om de database te droppen en een 
backup terug te zetten. Maar de container bleef niet eens lang genoeg actief om die acties uit te voeren.

Inmiddels heb ik hem omgezet naar `postgres:12` zoals je vroeg en daarna blijven beide containers goed draaien!

Nu alleen nog een manier vinden om de data terug te zetten... heb eerst de originele `./data/dsmrdb` map teruggezet, daar een databasedump van gemaakt en toen de stappen gevolgd die in de readme staan voor het wijzigen van een Postgres versie, maar dan krijg ik dit in DSMR:

`Geen gegevens gevonden. Zorg ervoor dat het dsmr_datalogger-proces draait of dat je gegevens aanlevert via die API. Daarnaast hoort het dsmr_backend-proces eveneens te draaien.`

**Comment by Tralapo** [comment]
In het mapje `./data/dsmr_backups` vond ik keurige `.sql.gz` backups per dag (duh), dus heb die van zondag nu teruggezet en alles werkt weer perfect! 

Toch vreemd dat `postgres:12-alpine` dan ineens zoveel problemen kan veroorzaken.

**Comment by Tralapo** [comment]
DSMR lijkt toch niet helemaal ongeschonden uit de strijd gekomen te zijn. Op het eerste gezicht leek het goed, omdat hij de actuele meterstanden gewoon toont.

Maar zoals het nu lijkt voert hij op de achtergrond niets uit. Er zijn geen live-grafieken en ook geen dag/uurtotalen van na gisteravond. Ook niet als ik die geplande processen via de interface laat uitvoeren.

Op de Status-pagina staan ook de volgende foutmeldingen, waarbij de teller steeds oploopt:

```
Te veel onverwerkte telegrammen: 16741   (2 dagen, 6 uur geleden)
Dagstatistieken lopen achter   (2 dagen, 10 uur geleden)
```

De log zegt het volgende:
```
2021-02-10 10:46:39,946 INFO spawned: 'dsmr_backend' with pid 2738
2021-02-10 10:46:40,951 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-10 10:46:59,031 INFO exited: dsmr_backend (exit status 0; expected)
2021-02-10 10:47:00,043 INFO spawned: 'dsmr_backend' with pid 2739
2021-02-10 10:47:01,047 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-10 10:47:17,468 INFO exited: dsmr_backend (exit status 0; expected)
2021-02-10 10:47:18,479 INFO spawned: 'dsmr_backend' with pid 2740
2021-02-10 10:47:19,484 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-10 10:47:36,522 INFO exited: dsmr_backend (exit status 0; expected)
2021-02-10 10:47:37,533 INFO spawned: 'dsmr_backend' with pid 2741
2021-02-10 10:47:38,539 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-10 10:47:54,677 INFO exited: dsmr_backend (exit status 0; expected)
2021-02-10 10:47:55,685 INFO spawned: 'dsmr_backend' with pid 2742
2021-02-10 10:47:56,759 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-10 10:48:13,702 INFO exited: dsmr_backend (exit status 0; expected)
2021-02-10 10:48:14,709 INFO spawned: 'dsmr_backend' with pid 2743
2021-02-10 10:48:15,713 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by xirixiz** [comment]
@Tralapo dit is meer een DSMR gerelateerde melding, dus niet zo zeer Docker. Wellicht kan @dennissiemensma hierbij assisteren?

**Comment by dennissiemensma** [comment]
@Tralapo ik denk dat je het beste even kunt zoeken naar de specifieke log voor het `dsmr_backend` proces. Ik verwacht dat daar een betere foutmelding in staat. 

Ik weet alleen niet precies waar die logs in de container staan. In de native installatie in `/var/log/supervisor/`.

**Comment by Tralapo** [comment]
Ik heb even `- ./data/dsmr_logs:/var/log/supervisor` toegevoegd aan de `volumes` voor dsmr, zodat de logs opgeslagen worden.

In `dsmr_backend.log` zie ik het volgende:

```
[2021-02-10 19:49:10,813] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2021-02-10 19:49:33,254] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2021-02-10 19:49:50,740] ERROR    (IntegrityError) dsmr_consumption.services.run errored: null value in column "delivered_1" violates not-null constraint
DETAIL:  Failing row contains (393381, 2021-02-08 04:00:00+01, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

[2021-02-10 19:49:52,033] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2021-02-10 19:50:11,348] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2021-02-10 19:50:28,883] ERROR    (IntegrityError) dsmr_consumption.services.run errored: null value in column "delivered_1" violates not-null constraint
DETAIL:  Failing row contains (393382, 2021-02-08 04:00:00+01, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

[2021-02-10 19:50:30,255] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2021-02-10 19:50:49,192] ERROR    CLIENTS: Run error: MQTT: Client no longer connected
```

Dat lijkt dan ineens weer op een probleem met MQTT?

**Comment by dennissiemensma** [comment]
Ik zie twee meldingen:
- IntegrityError
- MQTT-error (`failed to receive on socket: [Errno 32] Broken pipe`)

Het kan zijn dat de tweede een gevolg is van de eerste, maar dat weet ik niet zeker. De eerste lijkt aan te geven dat er een meting is met alleen een datumtijd, maar dat lijkt me vreemd en heb ik niet eerder gezien.

Ik denk dat je het beste even in de admin-interface kan kijken op `/admin/dsmr_datalogger/dsmrreading/` en eentje openen om te zien of de velden daar ook allemaal leeg zijn.

**Comment by Tralapo** [comment]
Er zijn 114 pagina's met un-processed lezingen daar en heb hier en daar steekproeven gedaan, maar ze zien er allemaal heel normaal uit. Zeker niet leeg.

**Comment by dennissiemensma** [comment]
Toevallig meldt iemand een soortgelijk issue via: dsmrreader/dsmr-reader/issues/1282

- Weet je nog wat voor soort backup je hebt teruggezet? Was dat een volledige of een partial?
- En kwam die backup van dezelfde DSMR-reader versie?

**Comment by Tralapo** [comment]
Zaterdag heb ik (zoals ik vaker doe) al m'n containers geüpdate, waarna de problemen begonnen.

Daarna heb ik, zoals hierboven besproken, de postgres-versie gewijzigd en via onderstaande methode één van de dagelijkse backups die DSRM zelf maakt teruggezet, die van vlak voor ik ging updaten.

Het is dus inderdaad wel zo dat de backup uit een oudere versie van DSMR komt dan de huidige.

```
docker-compose stop dsmr
docker exec -t dsmrdb dropdb dsmrreader -U dsmrreader
docker exec -t dsmrdb createdb -O dsmrreader dsmrreader -U dsmrreader
cat dsmrreader.sql | docker exec -i dsmrdb psql -U dsmrreader
docker-compose start dsmr
```

**Comment by dennissiemensma** [comment]
Oke ik denk dat je dan het beste even dat issue in DSMR-reader kan volgen.

**Comment by dennissiemensma** [comment]
@xirixiz ter debugging en vergelijking, wat zijn jouw resultaten als je dit uitvoert in je DSMR DB container:

```
grep timezone /var/lib/postgresql/data/postgresql.conf
```

En gebruik je env vars voor instellen tijdzone van de DSMR DB? Bijvoorbeeld:
```
  dsmrdb:
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
```

**Comment by xirixiz** [comment]
De output is dan:
```
-> docker exec -ti dsmrdb bash
bash-5.1# grep timezone /var/lib/postgresql/data/postgresql.conf
log_timezone = 'Europe/Amsterdam'
timezone = 'Europe/Amsterdam'
```

Verder zet ik alleen ```TZ=Europe/Amsterdam``` op zowel de PG als DSMR container. That's it. Ik zal ook eens even meekijken met het issue dat open staat, wellicht kan ik daar nog hulp bieden.

**Comment by MRL-33** [comment]
Ik loop ook steeds tegen deze foutmeldingen aan.
Nu heb ik alle containers/netwerken gestopt en verwijderd. (docker-compose down) Ook heb ik de submappen dsmr_backup & dsmrdb verwijderd.
Daarna heb alles weer opgestart met docker-compose pull & docker-compose up -d, maar krijg nog steeds een foutmelding in portainer.
`1970-05-02 03:22:16.010 CET [21] FATAL:  the database system is starting up

1970-05-02 03:22:16.010 CET [1] LOG:  startup process (PID 20) was terminated by signal 11: Segmentation fault

1970-05-02 03:22:16.010 CET [1] LOG:  aborting startup due to startup process failure

1970-05-02 03:22:16.010 CET [1] LOG:  database system is shut down`

Wat moet ik doen om alles te verwijderen?

**Comment by Tralapo** [comment]
Heb je geprobeerd om `postgres:12.4-alpine` als database in te stellen? Dat koste alles uiteindelijk op voor mij. [Zie deze issue](https://github.com/dsmrreader/dsmr-reader/issues/1282).

**Comment by MRL-33** [comment]
> Heb je geprobeerd om `postgres:12.4-alpine` als database in te stellen? Dat loste alles uiteindelijk op voor mij. [Zie ook deze issue](https://github.com/dsmrreader/dsmr-reader/issues/1282).

Het ziet er naar uit dat jou voorstel de oplossing is! Dankjewel. 
@xirixiz: Kan je dit ook duidelijk(er) opnemen/vermelden in jou docker-compose.yaml voor DSMR-reader?

**Comment by xirixiz** [comment]
Had ik al gedaan afgelopen week :)
