### ISSUE TITLE
Unable to start latest arm32v7 version

### ISSUE THREAD

**Issue by Nenodema** [xirixiz/dsmr-reader-docker#186]
## Setup/Architecture information
DSMR Running on a Raspberry PI, with a 10.5-alpine postgres database
Linux rbp1 5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux

## Version of the Docker image
xirixiz/dsmr-reader-docker:latest-2021.03.02-arm32v7

## Configuration

```yaml

version: '3.6'

services:
  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=**********
      - POSTGRES_PASSWORD=**********
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:work
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_LOGLEVEL=info
      - SD_AUTOSTART_DATALOGGER=true
      - SD_AUTORESTART_DATALOGGER=true
      - SD_AUTOSTART_BACKEND=true
      - SD_AUTORESTART_BACKEND=true
      - SD_AUTOSTART_MQTT=true
      - SD_AUTORESTART_MQTT=true
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/serial/by-id/usb-xxx

#volumes:
#   dsmrdb:
#   dsmrdb_backups:

```

## Describe the bug
Unable to start the latest arm32v7 version. DSMR version "DSMR-reader v4.12" runs without a problem.

@xirixiz 

**_Thanks btw for this great project!_**

## Debug log

```text

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all,
    self._result_cache = list(self._iterable_class(self)),
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__,
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size),
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql,
    cursor = self.connection.cursor(),
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner,
    event_loop = asyncio.get_event_loop(),
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop,
    self.set_event_loop(self.new_event_loop()),
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop,
    return self._loop_factory(),
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__,
    super().__init__(selector),
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__,
    super().__init__(),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__,
    self._clock_resolution = time.get_clock_info('monotonic').resolution,
PermissionError: [Errno 1] Operation not permitted,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/dsmr/manage.py", line 10, in <module>,
    execute_from_command_line(sys.argv),
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line,
    utility.execute(),
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 343, in run_from_argv,
    connections.close_all(),
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 237, in close_all,
    connection.close(),
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner,
    event_loop = asyncio.get_event_loop(),
  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop,
    self.set_event_loop(self.new_event_loop()),
  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop,
    return self._loop_factory(),
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__,
    super().__init__(selector),
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__,
    super().__init__(),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__,
    self._clock_resolution = time.get_clock_info('monotonic').resolution,
PermissionError: [Errno 1] Operation not permitted,
Exception ignored in: <function BaseEventLoop.__del__ at 0x762c31d8>,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__,
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__,
    f'closed={self.is_closed()} debug={self.get_debug()}>',
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug,
    return self._debug,
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug',
Exception ignored in: <function BaseEventLoop.__del__ at 0x762c31d8>,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 681, in __del__,
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self),
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 419, in __repr__,
    f'closed={self.is_closed()} debug={self.get_debug()}>',
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1909, in get_debug,
    return self._debug,
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug',

[ INFO ] Checking for NGINX SSL configuration...,

[ INFO ] ENABLE_NGINX_SSL is disabled, nothing to see here. Continuing...,

[ INFO ] Checking for HTTP AUTHENTICATION configuration...,

[ INFO ] ENABLE_HTTP_AUTH is disabled, nothing to see here. Continuing...,

[ INFO ] Configuring DSMR in standlone datalogger mode....,

[ INFO ] Starting supervisord...,

[ INFO ] Logfiles can be found at: /var/log/supervisor/*.log and /tmp/supervisord.log,
2021-03-15 11:12:47,231 INFO Set uid to user 0 succeeded,
2021-03-15 11:12:47,295 INFO RPC interface 'supervisor' initialized,
2021-03-15 11:12:47,297 INFO supervisord started with pid 16,
2021-03-15 11:12:48,304 INFO spawned: 'nginx' with pid 19,
2021-03-15 11:12:48,317 INFO spawned: 'dsmr_webinterface' with pid 20,
2021-03-15 11:12:48,327 INFO spawned: 'dsmr_datalogger' with pid 21,
2021-03-15 11:12:48,336 INFO spawned: 'dsmr_backend' with pid 22,
2021-03-15 11:12:49,664 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:12:49,665 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:12:49,665 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:12:51,682 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs),
2021-03-15 11:12:54,373 INFO exited: dsmr_backend (exit status 1; not expected),
2021-03-15 11:12:54,443 INFO spawned: 'dsmr_backend' with pid 28,
2021-03-15 11:12:54,445 INFO exited: dsmr_datalogger (exit status 1; not expected),
2021-03-15 11:12:55,451 INFO spawned: 'dsmr_datalogger' with pid 29,
2021-03-15 11:12:55,452 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:12:56,455 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:12:59,931 INFO exited: dsmr_backend (exit status 1; not expected),
2021-03-15 11:13:00,383 INFO spawned: 'dsmr_backend' with pid 30,
2021-03-15 11:13:01,092 INFO exited: dsmr_datalogger (exit status 1; not expected),
2021-03-15 11:13:02,098 INFO spawned: 'dsmr_datalogger' with pid 31,
2021-03-15 11:13:02,100 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:13:03,103 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:13:05,937 INFO exited: dsmr_backend (exit status 1; not expected),
2021-03-15 11:13:06,943 INFO spawned: 'dsmr_backend' with pid 32,
2021-03-15 11:13:07,666 INFO exited: dsmr_datalogger (exit status 1; not expected),
2021-03-15 11:13:08,673 INFO spawned: 'dsmr_datalogger' with pid 33,
2021-03-15 11:13:08,674 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-03-15 11:13:09,677 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),

```

```

Sorry, something unexptected happened

PermissionError: [Errno 1] Operation not permitted

File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)

  File "/dsmr/dsmr_frontend/mixins.py", line 10, in dispatch
    if not FrontendSettings.get_solo().always_require_login:

  File "/usr/local/lib/python3.9/site-packages/solo/models.py", line 55, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()

  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 19, in inner
    event_loop = asyncio.get_event_loop()

  File "/usr/local/lib/python3.9/asyncio/events.py", line 639, in get_event_loop
    self.set_event_loop(self.new_event_loop())

  File "/usr/local/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()

  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)

  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 55, in __init__
    super().__init__()

  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution

```

**Comment by xirixiz** [comment]
Fixed! Check the latest release

**Comment by Nenodema** [comment]
Thanks Bram, works great now!

**Comment by KenwoodFox** [comment]
What fixed it?
