### ISSUE TITLE
Database start niet meer - aborting startup due to startup process failure

### ISSUE THREAD

**Issue by NickG92** [xirixiz/dsmr-reader-docker#198]
Ik heb dsmrreader draaiende op een Raspberry pi dmv docker. Na een herstart van het gehele systeem vandaag wil de container niet meer opstarten omdat, voor zover ik kan zien, de database server niet wil starten. Ik gebruik het standaard docker-compose.yaml voorbeeld zoals in de repo te zien is. De foutmelding die ik krijg is:
```
dsmrdb_1  |
dsmrdb_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
dsmrdb_1  |
dsmrdb_1  | 2021-03-25 17:43:35.865 CET [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 8.3.0-6) 8.3.0, 32-bit
dsmrdb_1  | 2021-03-25 17:43:35.867 CET [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
dsmrdb_1  | 2021-03-25 17:43:35.867 CET [1] LOG:  listening on IPv6 address "::", port 5432
dsmrdb_1  | 2021-03-25 17:43:35.887 CET [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dsmrdb_1  | 2021-03-25 17:43:36.002 CET [28] FATAL:  the database system is starting up
dsmr_1    | Traceback (most recent call last):
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
dsmr_1    |     self.connect()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
dsmr_1    |     self.connection = self.get_new_connection(conn_params)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
dsmr_1    |     connection = Database.connect(**conn_params)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
dsmr_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
dsmr_1    | psycopg2.OperationalError: FATAL:  the database system is starting up
dsmr_1    |
dsmr_1    |
dsmr_1    | The above exception was the direct cause of the following exception:
dsmr_1    |
dsmr_1    | Traceback (most recent call last):
dsmr_1    |   File "/dsmr/manage.py", line 10, in <module>
dsmr_1    |     execute_from_command_line(sys.argv)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
dsmr_1    |     utility.execute()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
dsmr_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
dsmr_1    |     self.execute(*args, **cmd_options)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
dsmr_1    |     output = self.handle(*args, **options)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
dsmr_1    |     res = handle_func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 92, in handle
dsmr_1    |     executor = MigrationExecutor(connection, self.migration_progress_callback)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
dsmr_1    |     self.loader = MigrationLoader(self.connection)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
dsmr_1    |     self.build_graph()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
dsmr_1    |     self.applied_migrations = recorder.applied_migrations()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
dsmr_1    |     if self.has_table():
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
dsmr_1    |     with self.connection.cursor() as cursor:
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
dsmr_1    |     return self._cursor()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
dsmr_1    |     self.ensure_connection()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
dsmr_1    |     self.connect()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
dsmr_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
dsmr_1    |     self.connect()
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
dsmr_1    |     self.connection = self.get_new_connection(conn_params)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
dsmr_1    |     return func(*args, **kwargs)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
dsmr_1    |     connection = Database.connect(**conn_params)
dsmr_1    |   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
dsmr_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
dsmr_1    | django.db.utils.OperationalError: FATAL:  the database system is starting up
dsmr_1    |
dsmrdb_1  | 2021-03-25 17:43:47.252 CET [1] LOG:  startup process (PID 27) was terminated by signal 11: Segmentation fault
dsmrdb_1  | 2021-03-25 17:43:47.252 CET [1] LOG:  aborting startup due to startup process failure
dsmrdb_1  | 2021-03-25 17:43:47.385 CET [1] LOG:  database system is shut down
dsmr_dsmrdb_1 exited with code 1
dsmrdb_1  | 2021-03-25 17:43:59.078 CET [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
dsmrdb_1  | 2021-03-25 17:44:10.695 CET [1] LOG:  startup process (PID 27) was terminated by signal 11: Segmentation fault
dsmrdb_1  | 2021-03-25 17:44:10.695 CET [1] LOG:  aborting startup due to startup process failure
dsmrdb_1  | 2021-03-25 17:44:10.787 CET [1] LOG:  database system is shut down
dsmr_1    |
dsmr_1    | 562 static files copied to '/var/www/dsmrreader/static'.
dsmr_dsmrdb_1 exited with code 1
```
Van alles inmiddels al geprobeerd maar ik krijg hem niet meer gestart. Is de DB corrupt?

**Comment by xirixiz** [comment]
Dat is enigszins vreemd. Kan je wellicht ook jouw docker run / docker-compose content delen?
Bij het starten van postgres wordt er al een database gezien, maar mogelijk is er iets mis met de rechten.

Ik weet dat er ook issues zijn, of zijn geweest, met de docker alpine:postgres image. Zelf ben ik om die reden overgestapt op de niet Alpine versie van Postgres (zie docker-compose voorbeeld).

**Comment by NickG92** [comment]
Inhoud van docker-compose.yaml
```
version: '3.8'

services:
  dsmrdb:
    image: postgres:12-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmrdb:/var/lib/postgresql/data
      - ./dsmrdb_backups:/dsmrdb/backups
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
    #build: .
    image: xirixiz/dsmr-reader-docker:latest
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

#volumes:
#   dsmrdb:
#   dsmrdb_backups:
```

**Comment by xirixiz** [comment]
Probeer het eens met postgres:12 image.

**Comment by NickG92** [comment]
Ik heb het inmiddels anders opgelost, met een frisse start. Het is niet mijn eigen setup wat het wat lastig maakte in de communicatie.

Toch bedankt voor de poging @xirixiz !
