### ISSUE TITLE
2021.12 branch breaks if system doesn't use USB

### ISSUE THREAD

**Issue by marcelvanveen** [xirixiz/dsmr-reader-docker#232]
### Issue

Hi,

I'm using this image for processing and displaying, but *not* for retrieving the data from the P1 meter itself (I use the remote API functionality of DSMR for that). Since the supervisord rewrite in 2021.12, using this mechanism breaks: if the USB datalogger dies, supervisord will restart all the other processes as well...

### Which version has the issue?

2021.12.01 / 2 / 3

### What was the last working version?

latest-2021.10.02-amd64

### What type of installation are you running (architecture)?

AMD64

### Anything in the logs that might be useful?

```txt
dsmr-reader  | [2021-12-17 09:02:37 +0100] [28] [INFO] Booting worker with pid: 28
dsmr-reader  | Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
dsmr-reader  | Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
dsmr-reader  | 2021-12-17 09:02:37,922 ERROR    mixins       run_once                        103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
dsmr-reader  |   File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
dsmr-reader  |     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
dsmr-reader  | FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyUSB0'
dsmr-reader  | 
dsmr-reader  | During handling of the above exception, another exception occurred:
dsmr-reader  | 
dsmr-reader  | Traceback (most recent call last):
dsmr-reader  |   File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 34, in read_telegram
dsmr-reader  |     serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
dsmr-reader  |   File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
dsmr-reader  |     instance.open()
dsmr-reader  |   File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
dsmr-reader  |     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
dsmr-reader  | serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
dsmr-reader  | 
dsmr-reader  | During handling of the above exception, another exception occurred:
dsmr-reader  | 
dsmr-reader  | Traceback (most recent call last):
dsmr-reader  |   File "/dsmr/dsmr_backend/mixins.py", line 92, in run_once
dsmr-reader  |     self.run(data=self.data, **options)
dsmr-reader  |   File "/dsmr/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
dsmr-reader  |     telegram = next(self.telegram_generator)
dsmr-reader  |   File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 36, in read_telegram
dsmr-reader  |     raise RuntimeError('Failed to connect: {}', error)
dsmr-reader  | RuntimeError: ('Failed to connect: {}', SerialException(2, "could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'"))
dsmr-reader  | 
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO exited: dsmr_datalogger (exit status 0; expected)
dsmr-reader  | 2021-12-17 09:02:38,553 INFO exited: dsmr_datalogger (exit status 0; expected)
dsmr-reader  | 2021-12-17 09:02:38,555 INFO spawned: 'dsmr_datalogger' with pid 29
dsmr-reader  | 2021-12-17 09:02:38,555 INFO spawned: 'dsmr_datalogger' with pid 29
dsmr-reader  | 2021-12-17 09:02:38,555 WARN received SIGQUIT indicating exit request
dsmr-reader  | 2021-12-17 09:02:38,555 WARN received SIGQUIT indicating exit request
dsmr-reader  | 2021-12-17 09:02:38,556 INFO waiting for processes, dsmr_backend, dsmr_datalogger, dsmr_webinterface, nginx to die
dsmr-reader  | 2021-12-17 09:02:38,556 INFO waiting for processes, dsmr_backend, dsmr_datalogger, dsmr_webinterface, nginx to die
dsmr-reader  | 2021-12-17 09:02:38,610 INFO stopped: nginx (exit status 0)
dsmr-reader  | 2021-12-17 09:02:38,610 INFO stopped: nginx (exit status 0)
dsmr-reader  | [2021-12-17 09:02:38 +0100] [22] [INFO] Handling signal: term
dsmr-reader  | [2021-12-17 09:02:38 +0100] [28] [INFO] Worker exiting (pid: 28)
dsmr-reader  | [2021-12-17 09:02:38 +0100] [22] [INFO] Shutting down: Master
dsmr-reader  | 2021-12-17 09:02:38,834 INFO stopped: dsmr_webinterface (exit status 0)
dsmr-reader  | 2021-12-17 09:02:38,834 INFO stopped: dsmr_webinterface (exit status 0)
dsmr-reader  | Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
dsmr-reader  | 2021-12-17 09:02:39,124 INFO stopped: dsmr_datalogger (terminated by SIGTERM)
dsmr-reader  | 2021-12-17 09:02:39,124 INFO stopped: dsmr_datalogger (terminated by SIGTERM)
dsmr-reader  | 2021-12-17 09:02:40,055 INFO stopped: dsmr_backend (exit status 0)
dsmr-reader  | 2021-12-17 09:02:40,055 INFO stopped: dsmr_backend (exit status 0)
dsmr-reader  | 2021-12-17 09:02:40,055 INFO stopped: processes (terminated by SIGTERM)
dsmr-reader  | 2021-12-17 09:02:40,055 INFO stopped: processes (terminated by SIGTERM)
```

**Comment by xirixiz** [comment]
Can you share your compose file?

Do you have these vars set properly? https://github.com/xirixiz/dsmr-reader-docker#dsmr-datalogger-related

**Comment by marcelvanveen** [comment]
Ha! That pointed me in the right direction. For future reference: I was missing `DATALOGGER=receiver`. Seems that didn't fully break things in 2021.10, but it does on 2021.12 (probably due to supervisord taking down other processes). Thanks for the quick response and all of your work!
