### ISSUE TITLE
Datalogger network host en port worden niet goed doorgegeven?

### ISSUE THREAD

**Issue by Flight777** [xirixiz/dsmr-reader-docker#241]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/dsmr-reader-docker/blob/master/.github/SUPPORT.md)

### I've found an issue and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Ik probeer DSMR Reader (na jaren succesvol met de API te draaien) over te krijgen naar ser2net, ivm met ook een direct connectie naar Home Assistant. Echter lijkt het alsof de environment variable DATALOGGER_NETWORK_HOST en DATALOGGER_NETWORK_PORT niet goed worden doorgegeven. De Logger gaat namelijk nat op het resolven van een leeg path (zie onder in de container log).

Ik draai overigens op Unraid, dus ziet er iets anders uit qua Docker opzet dan je waarschijnlijk gewend bent.

### Expected behaviour

Network path en port worden ingevuld.

### Actual behaviour

Lijken niet te worden ingevuld, zie container log.

### Steps to reproduce

DATALOGGER_INPUT_METHOD = ipv4
DATALOGGER_NETWORK_HOST = x.x.x.x
DATALOGGER_NETWORK_PORT = x

### Docker info

```yaml
`Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 38
  Running: 33
  Paused: 0
  Stopped: 5
 Images: 40
 Server Version: 20.10.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.28-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 23.43GiB
 Name: LS15mainframe
 ID: TOJI:A6EY:464B:YZD3:BTKN:QUTB:H2K7:YBHM:L4CW:FTKC:NB7H:6YXI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine`
```

### Version

UNRAID 6.9.2

### Docker compose

![image](https://user-images.githubusercontent.com/5236143/146974304-9aec4ef2-253d-40e0-a225-21632fb3fb40.png)

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='DSMRReader' --net='bridge' -e TZ="Europe/Berlin" 
-e HOST_OS="Unraid" 
-e 'DJANGO_DATABASE_HOST'='192.168.31.10' 
-e 'DSMRREADER_ADMIN_USER'='admin' 
-e 'DSMRREADER_ADMIN_PASSWORD'='********' 
-e 'DATALOGGER_MODE'='standalone' 
-e 'DATALOGGER_INPUT_METHOD'='ipv4' 
-e 'DJANGO_X_FRAME_OPTIONS'='ALLOWALL' 
-e 'VACUUM_DB_ON_STARTUP'='true' 
-e 'DATALOGGER_NETWORK_HOST'='192.168.31.8' 
-e 'DATALOGGER_NETWORK_PORT'='2001' 
-e 'DATALOGGER_DEBUG_LOGGING'='true' 
-e 'VIRTUAL_HOST'='localhost' 
-e 'DJANGO_DATABASE_PORT'='5432' 
-e 'DJANGO_DATABASE_NAME'='dsmrdb' 
-e 'DATALOGGER_SLEEP'='10' 
-e 'PUID'='99' 
-e 'PGID'='100' 
-e 'SD_USER'='nobody' 
-e 'SD_GROUP'='users' 
-p '7777:80/tcp' 
-v '/mnt/user/appdata/dsmr-reader/backups':'/home/dsmr/app/backups':'rw' 
'xirixiz/dsmr-reader-docker'
5f74bee6ab132cdc06af576d491287c366a891e93d49529192b88374a4268d8d
```

### Container logs

```
Starting DSMR Reader - datalogger...
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

2021-12-21 18:29:32,763 ERROR mixins run_once 103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):

File "/usr/local/lib/python3.10/site-packages/serial/urlhandler/protocol_socket.py", line 63, in open
self._socket = socket.create_connection(self.from_url(self.portstr), timeout=POLL_TIMEOUT)
File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 34, in read_telegram
serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
instance.open()
File "/usr/local/lib/python3.10/site-packages/serial/urlhandler/protocol_socket.py", line 66, in open
raise SerialException("Could not open port {}: {}".format(self.portstr, msg))
serial.serialutil.SerialException: Could not open port socket://None:23: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dsmr/dsmr_backend/mixins.py", line 92, in run_once
self.run(data=self.data, **options)
File "/dsmr/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
telegram = next(self.telegram_generator)
File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 36, in read_telegram
raise RuntimeError('Failed to connect: {}', error)

RuntimeError: ('Failed to connect: {}', SerialException('Could not open port socket://None:23: [Errno -2] Name does not resolve'))
```

**Comment by xirixiz** [comment]
Hmm, mogelijk heeft dit met de switch naar s6 overlay te maken. Kan je eens testen met een oudere image:

- Deze: amd64-2021.12.04
- Of deze: amd64-2021.12.03

Die zijn namelijk nog gebasseerd of  supervisord. Mogelijk weet @dennissiemensma of dit ermee te maken heeft.

**Comment by Flight777** [comment]
Meteen even geprobeerd, maar zelfde issue :( 

```
vacuumdb: vacuuming database "dsmrdb"
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.

563 static files copied to '/var/www/dsmrreader/static'.
Updating password of superuser "admin"
Deactivating any other existing superusers
2021-12-21 20:22:50,340 INFO Set uid to user 0 succeeded
2021-12-21 20:22:50,347 INFO RPC interface 'supervisor' initialized
2021-12-21 20:22:50,347 INFO supervisord started with pid 1
2021-12-21 20:22:51,350 INFO spawned: 'processes' with pid 20
2021-12-21 20:22:51,352 INFO spawned: 'dsmr_backend' with pid 21
2021-12-21 20:22:51,353 INFO spawned: 'dsmr_datalogger' with pid 22
2021-12-21 20:22:51,355 INFO spawned: 'dsmr_webinterface' with pid 23
2021-12-21 20:22:51,356 INFO spawned: 'nginx' with pid 24
[2021-12-21 20:22:51 +0100] [23] [INFO] Starting gunicorn 20.1.0
[2021-12-21 20:22:51 +0100] [23] [INFO] Listening at: unix:/var/tmp/gunicorn--dsmr_webinterface.socket (23)
[2021-12-21 20:22:51 +0100] [23] [INFO] Using worker: sync
[2021-12-21 20:22:51 +0100] [29] [INFO] Booting worker with pid: 29
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

2021-12-21 20:22:52,000 ERROR mixins run_once 103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):

File "/usr/local/lib/python3.10/site-packages/serial/urlhandler/protocol_socket.py", line 63, in open
self._socket = socket.create_connection(self.from_url(self.portstr), timeout=POLL_TIMEOUT)
File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 34, in read_telegram
serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
instance.open()
File "/usr/local/lib/python3.10/site-packages/serial/urlhandler/protocol_socket.py", line 66, in open
raise SerialException("Could not open port {}: {}".format(self.portstr, msg))
serial.serialutil.SerialException: Could not open port socket://None:23: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dsmr/dsmr_backend/mixins.py", line 92, in run_once
self.run(data=self.data, **options)
File "/dsmr/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
telegram = next(self.telegram_generator)
File "/dsmr/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 36, in read_telegram
raise RuntimeError('Failed to connect: {}', error)

RuntimeError: ('Failed to connect: {}', SerialException('Could not open port socket://None:23: [Errno -2] Name does not resolve'))


Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

2021-12-21 20:22:52,148 ERROR services run 37 | No recent gas reading found

Traceback (most recent call last):
File "/dsmr/dsmr_mindergas/services.py", line 69, in export
last_gas_reading = GasConsumption.objects.filter(
File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 325, in __getitem__
return qs._result_cache[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/dsmr/dsmr_mindergas/services.py", line 35, in run
export()
File "/dsmr/dsmr_mindergas/services.py", line 74, in export
raise AssertionError(_('No recent gas reading found'))
AssertionError: No recent gas reading found
2021-12-21 20:22:53,151 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-21 20:22:53,151 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-21 20:22:53,151 INFO success: dsmr_datalogger entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-21 20:22:55,153 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2021-12-21 20:22:57,155 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2021-12-21 20:23:02,148 INFO exited: dsmr_datalogger (exit status 0; expected)
2021-12-21 20:23:04,151 WARN received SIGQUIT indicating exit request
2021-12-21 20:23:04,151 INFO waiting for processes, dsmr_backend, dsmr_webinterface, nginx to die
2021-12-21 20:23:04,167 INFO stopped: nginx (exit status 0)
[2021-12-21 20:23:04 +0100] [29] [INFO] Worker exiting (pid: 29)
[2021-12-21 20:23:04 +0100] [23] [INFO] Handling signal: term
[2021-12-21 20:23:04 +0100] [23] [INFO] Shutting down: Master
2021-12-21 20:23:04,390 INFO stopped: dsmr_webinterface (exit status 0)
2021-12-21 20:23:07,386 INFO stopped: dsmr_backend (exit status 0)
2021-12-21 20:23:07,386 INFO waiting for processes to die
2021-12-21 20:23:07,386 INFO stopped: processes (terminated by SIGTERM)
```

**Comment by xirixiz** [comment]
Oke, dat is voor mij iig goed nieuws 😄. Even wachten op de reactie van Dennis... mogelijk dat hij nog iets weet alvorens ik de diepte in ga.

**Comment by Flight777** [comment]
Ik weet niet of dit gerelateerd is, maar sowieso loopt de container voor geen meter (sorry :P) na de update. (ik denk dat ik eerst een versie van november ergens draaide). Als ik hem weer omzet naar receiver, crashed hij steeds op iets met MQTT... dit terwijl hier in de settings niets aan is veranderd:

```
021-12-21 21:12:01,109 INFO spawned: 'nginx' with pid 24
[2021-12-21 21:12:01 +0100] [23] [INFO] Starting gunicorn 20.1.0
[2021-12-21 21:12:01 +0100] [23] [INFO] Listening at: unix:/var/tmp/gunicorn--dsmr_webinterface.socket (23)
[2021-12-21 21:12:01 +0100] [23] [INFO] Using worker: sync
[2021-12-21 21:12:01 +0100] [29] [INFO] Booting worker with pid: 29
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html

2021-12-21 21:12:02,734 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-21 21:12:02,734 INFO success: dsmr_backend entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-12-21 21:12:04,736 INFO success: dsmr_webinterface entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2021-12-21 21:12:06,738 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2021-12-21 21:22:51,171 ERROR persistent_clients run 38 | CLIENTS: Run error: MQTT: Client loop() failed, requesting restart to prevent waiting forever...

2021-12-21 21:22:52,317 INFO exited: dsmr_backend (exit status 0; expected)
2021-12-21 21:22:54,321 WARN received SIGQUIT indicating exit request
2021-12-21 21:22:54,321 INFO waiting for processes, dsmr_webinterface, nginx to die
2021-12-21 21:22:54,340 INFO stopped: nginx (exit status 0)
[2021-12-21 21:22:54 +0100] [29] [INFO] Worker exiting (pid: 29)
[2021-12-21 21:22:54 +0100] [23] [INFO] Handling signal: term
[2021-12-21 21:22:54 +0100] [23] [INFO] Shutting down: Master
2021-12-21 21:22:54,566 INFO stopped: dsmr_webinterface (exit status 0)
2021-12-21 21:22:57,569 INFO waiting for processes to die
2021-12-21 21:22:57,569 INFO stopped: processes (terminated by SIGTERM)
vacuumdb: vacuuming database "dsmrdb"
Operations to perform:
Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_dropbox, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
No migrations to apply.
```

**Comment by dennissiemensma** [comment]
@Flight777 het is mij niet helemaal duidelijk welke datalogger je wilt gebruiken. De **remote datalogger** werkt met env vars, de **ingebouwde** netwerk-datalogger in DSMR-reader zelf werkt via de admin-interface.

Mocht je DSMR-reader zelf willen laten lezen van ser2net, dan kun je dat hier instellen.
- `/admin/dsmr_datalogger/dataloggersettings/1/change/`

![Screenshot from 2021-12-21 21-27-52](https://user-images.githubusercontent.com/16581744/146993475-18ee26fb-448a-4f2c-ae78-a97c52e4d874.png)

_Mocht dat niet zijn wat je wilt, dan zullen we verder moeten zoeken, maar in principe heb je de remote datalogger alleen nodig wanneer DSMR-reader niet bij de seriele poort kan (of niet bij ser2net)._

**Comment by dennissiemensma** [comment]
@xirixiz weet jij trouwens waarom de container stopt bij een fout in het backend-proces, of lijkt dat maar zo? 

Ik zit er niet heel diep in, maar laatst zag ik hetzelfde bij: https://github.com/dsmrreader/dsmr-reader/discussions/1539#discussioncomment-1827370

**Comment by Flight777** [comment]
@dennissiemensma Bedankt voor je input! :)

Ik draaide altijd op de **remote datalogger**, maar wil nu ik toch weer de container wilde upgraden meteen naar ser2net overstappen en dus de **ingebouwde datalogger** (vanwege het willen hebben van meerdere connecties naar de seriele poort omdat ik ook HA direct wil koppelen, leek dit mij de beste manier). 

Volgens de documentatie moet ik dit doen met de volgende variabelen:

DATALOGGER_MODE=standalone
DATALOGGER_INPUT_METHOD=ipv4
DATALOGGER_NETWORK_HOST=x.x.x.x
DATALOGGER_NETWORK_PORT=x

Bij het opstarten van de container lijken dat host adres en poort op één of andere manier niet geparsed te worden. Of is via de UI nu nog de enige werkende manier?

**Comment by dennissiemensma** [comment]
Die envvars, die zijn voor de remote datalogger. 

Ik zou dit proberen om je GUI weer up te krijgen: https://github.com/dsmrreader/dsmr-reader/discussions/1539#discussioncomment-1827370

Daarna kun je navigeren naar `/admin/dsmr_datalogger/dataloggersettings/1/change/` en de ingebouwde datalogger instellen op ser2net.

**Comment by dennissiemensma** [comment]
In v5.x gaan die envvars trouwens hernoemd wordt, juist omdat het verwarrend is: https://github.com/dsmrreader/dsmr-reader/commit/9b916a7802adff4f75111ad1b9314387ce4ed463#diff-e8c042ae347840c231ce796902211457445bbdd2c451105a7a25ea79d7388332

Dus ik snap de verwarring helemaal.

**Comment by Flight777** [comment]
Thanks, ga dat even proberen, maar wat betreft die ENVVARS, dat is toch juist om de datalogger in te stellen (al dan remote of standalone?)

![image](https://user-images.githubusercontent.com/5236143/146994804-427978af-5333-4175-a266-0a76ea95abb7.png)

**Comment by dennissiemensma** [comment]
Dat kan Xirixiz denk ik beter uitleggen. Als ik het zo 1-2-3 zie in de code dan bepaalt de datalogger mode meer of het dsmr_datalogger proces moet draaien of het remote datalogger script. 

De rest van de verwarring komt omdat ik in het verleden de envvars van het remote datalogger script niet geprefixed met met `REMOTE_`, wat straks dus wel gaat gebeuren.

**Comment by Flight777** [comment]
Ok, ik heb de ser2net nu aan de praat via de GUI. Ik kan wel bevestigen dat met die ENV Vars de input mode al op ipv4 was gezet, alleen dus inderdaad (ook in de GUI) IP leeg is gebleven en de port op default 23 staat.

De SLEEP env var is ook gewoon netjes overgenomen. Dus ik denk dat @xirixiz opzich wel toestaat om het via de container in te stellen, echter er iets niet helemaal goed gaat ;)

Maar inderdaad, de nieuwe namen zijn sowieso zo een plus!

Nu alleen nog het MQTT raadsel, staat nu weer aan (na het eerst via de DB zoals beschreven uit te zetten), en lijkt het weer te doen. Maar waarom was dit uberhaubt een issue na de update, aannemende dat hij het nu weer blijft doen natuurlijk anders ben ik zo weer terug? :P

Bedankt voor alle vlotte hulp vanavond!

**Comment by xirixiz** [comment]
Hi, ik kan het voor de UI niet aanpassen via Docker inderdaad omdat die waarden in de DB staan. Dus met de ENV vars staan de processen en basis goed om het verder af te configureren via de UI. Het enige dat ik kan doen is het te vermelden in de documentatie dat bij het gebruik van deze setup ook nog handmatig het eea geconfigureerd moet worden.

Eigenlijk is dat ook zo voor de DSMR versie en USB settings. Ik kan het wel in de DB aanpassen, maar dan wordt het beheer van dit project steeds ingewikkelder. Wellicht moet ik daar een keer met Dennis over spreken en is kunnen we een mooie oplossing bedenken zodat de Docker variant en de "gewone" variant wat meer met elkaar verbonden zijn.

@dennissiemensma Bedankt voor weer voor de vlotte support!

**Comment by dennissiemensma** [comment]
> Eigenlijk is dat ook zo voor de DSMR versie en USB settings. Ik kan het wel in de DB aanpassen, maar dan wordt het beheer van dit project steeds ingewikkelder. Wellicht moet ik daar een keer met Dennis over spreken en is kunnen we een mooie oplossing bedenken zodat de Docker variant en de "gewone" variant wat meer met elkaar verbonden zijn.

Laten we daar inderdaad een keertje over brainstormen! Ik ben inmiddels weer wat meer bekender geworden met Docker, maar nog lang niet in de zin van wat een handige setup is en wat niet. 

Dit is al een brainfart:

Wellicht helpt het om alle processen uit 1 draaiende container te halen en ipv daarvan de container 2 of 3 keer te draaien met andere commands (afhankelijk van wat de gebruiker nodig heeft).

- Dan zou iemand 1 container kunnen draaien (zonder DB) met alleen de remote datalogger (kan ik wel iets voor maken qua command denk ik). 
- Of iemand draait de DB met 3x de container met elk een ander command (datalogger, backend, GUI). 
- Of iemand draait de DB met 2x de container met de backend en GUI en gebruikt de API van DSMR-reader om metingen in te voeren.

Als een van de processen/containers crasht, heeft de rest er geen last van. Eigenlijk net zoals met Supervisor (of systemd) in de niet-Docker-versie. Nadeel is uiteraard dan wel dat de container meerdere keren moet draaien, maar wellicht is dat wel werkbaar met Alpine.
